
import { Loan, RepaymentStatus, PayoutMethod, Language, ApplicationStatus, LoanTemplate } from './types';

export const DEFAULT_INTEREST_RATE = 30;
export const DEFAULT_PENALTY_RATE = 5;

export const LOAN_TEMPLATES: LoanTemplate[] = [
  {
    id: 'startup',
    label: 'Business Stock',
    labelXh: 'Isitokhwe Somsebenzi',
    amount: 5000,
    purpose: 'Buying bulk stock for small business resale.',
    purposeXh: 'Ukuthenga isitokhwe somsebenzi omncinci.'
  },
  {
    id: 'transport',
    label: 'Transport / Taxi',
    labelXh: 'Uthutho / Itekisi',
    amount: 1200,
    purpose: 'Monthly commute and taxi fare for work.',
    purposeXh: 'Imali yothutho yenyanga yomsebenzi.'
  },
  {
    id: 'emergency',
    label: 'Emergency / Household',
    labelXh: 'Ingxakeko / Ikhaya',
    amount: 800,
    purpose: 'Urgent household repairs or grocery shortfall.',
    purposeXh: 'Iinkcitho zangaphakathi ezingalindelekanga.'
  },
  {
    id: 'education',
    label: 'School Fees / Stationery',
    labelXh: 'Imfundo / Iincwadi',
    amount: 2500,
    purpose: 'School uniforms, books, or registration fees.',
    purposeXh: 'Iyunifomu yesikolo, iincwadi okanye umrhumo.'
  }
];

export const SA_BANKS = [
  'Standard Bank',
  'First National Bank (FNB)',
  'Absa',
  'Nedbank',
  'Capitec Bank',
  'TymeBank',
  'Discovery Bank',
  'Bank Zero',
  'African Bank',
  'Investec',
  'Bidvest Bank',
  'Sasfin Bank',
  'Grindrod Bank',
  'Postbank',
  'Old Mutual Bank',
  'Mercantile Bank',
  'Al Baraka Bank',
  'HBZ Bank',
  'Access Bank South Africa'
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'T001',
    borrowerName: 'Ms S Nkila',
    idNumber: '9201010001081',
    physicalAddress: 'East London, South Africa',
    borrowerNumber: '0660710211',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2025-11-15',
    dueDate: '2025-12-01',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '20% for Aretha',
    history: [
      { date: '2025-11-15', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-12-01', action: 'Full Repayment Received', amount: 520 }
    ]
  },
  {
    id: 'T002',
    borrowerName: 'Ms A Gwavu',
    idNumber: '8805120002084',
    physicalAddress: 'Qonce, South Africa',
    borrowerNumber: '0694266153',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2025-11-15',
    dueDate: '2025-11-25',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '20% for Aretha',
    history: [
      { date: '2025-11-15', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-11-25', action: 'Full Repayment Received', amount: 520 }
    ]
  },
  {
    id: 'T003',
    borrowerName: 'Ms Seekane',
    idNumber: '9506150003087',
    physicalAddress: 'Mthatha, South Africa',
    borrowerNumber: '0691960577',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 200,
    interestRate: 60,
    penaltyRate: 5,
    totalRepayment: 320,
    startDate: '2025-11-16',
    dueDate: '2025-11-30',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-11-16', action: 'Loan Disbursed', amount: 200 },
      { date: '2025-11-30', action: 'Full Repayment Received', amount: 320 }
    ]
  },
  {
    id: 'T004',
    borrowerName: 'Mr Moyakhe',
    idNumber: '8204200004082',
    physicalAddress: 'Gqeberha, South Africa',
    borrowerNumber: '0815676183',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 250,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 325,
    startDate: '2025-11-16',
    dueDate: '2025-11-25',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '20% for Aretha',
    history: [
      { date: '2025-11-16', action: 'Loan Disbursed', amount: 250 },
      { date: '2025-11-25', action: 'Full Repayment Received', amount: 325 }
    ]
  },
  {
    id: 'T005',
    borrowerName: 'Simphiwe',
    idNumber: '9008280005089',
    physicalAddress: 'East London, South Africa',
    borrowerNumber: '0634804576',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2025-11-18',
    dueDate: '2025-11-25',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-11-18', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-11-25', action: 'Full Repayment Received', amount: 520 }
    ]
  },
  {
    id: 'T006',
    borrowerName: 'Tito',
    idNumber: '8511100006085',
    physicalAddress: 'Butterworth, South Africa',
    borrowerNumber: '0605679674',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 1500,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 1950,
    startDate: '2025-11-07',
    dueDate: '2025-11-30',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-11-07', action: 'Loan Disbursed', amount: 1500 },
      { date: '2025-11-30', action: 'Full Repayment Received', amount: 1950 }
    ]
  },
  {
    id: 'T007',
    borrowerName: 'Tito',
    idNumber: '8511100006085',
    physicalAddress: 'Butterworth, South Africa',
    borrowerNumber: '0605679674',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 500,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 650,
    startDate: '2025-11-09',
    dueDate: '2025-11-30',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-11-09', action: 'Loan Disbursed', amount: 500 },
      { date: '2025-11-30', action: 'Full Repayment Received', amount: 650 }
    ]
  },
  {
    id: 'T008',
    borrowerName: 'Viwe',
    idNumber: '9403120007083',
    physicalAddress: 'Alice, South Africa',
    borrowerNumber: '0768014266',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 500,
    interestRate: 0,
    penaltyRate: 5,
    totalRepayment: 500,
    startDate: '2025-10-03',
    dueDate: '2025-10-17',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    history: [
      { date: '2025-10-03', action: 'Loan Disbursed', amount: 500 },
      { date: '2025-10-17', action: 'Full Repayment Received', amount: 500 }
    ]
  },
  {
    id: 'T009',
    borrowerName: 'Aretha',
    idNumber: '9104050012089',
    physicalAddress: 'Beacon Bay, East London',
    borrowerNumber: '0740124606',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 3000,
    interestRate: 0,
    penaltyRate: 5,
    totalRepayment: 3000,
    startDate: '2025-12-02',
    dueDate: '2025-12-05',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-02', action: 'Loan Disbursed', amount: 3000 },
      { date: '2025-12-05', action: 'Full Repayment Received', amount: 3000 }
    ]
  },
  {
    id: 'T010',
    borrowerName: 'A Mangweni',
    idNumber: '8907120013081',
    physicalAddress: 'Zwelitsha, King Williams Town',
    borrowerNumber: '0840704310',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 500,
    interestRate: 50,
    penaltyRate: 5,
    totalRepayment: 750,
    startDate: '2025-12-02',
    dueDate: '2025-12-15',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-02', action: 'Loan Disbursed', amount: 500 },
      { date: '2025-12-15', action: 'Full Repayment Received', amount: 750 }
    ]
  },
  {
    id: 'T011',
    borrowerName: 'U Zokhela',
    idNumber: '9611200014087',
    physicalAddress: 'Mdantsane, South Africa',
    borrowerNumber: '0730713439',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 3000,
    interestRate: 60,
    penaltyRate: 5,
    totalRepayment: 4800,
    startDate: '2025-12-01',
    dueDate: '2025-12-20',
    status: RepaymentStatus.OVERDUE,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '40% for Aretha',
    history: [
      { date: '2025-12-01', action: 'Loan Disbursed', amount: 3000 }
    ]
  },
  {
    id: 'T012',
    borrowerName: 'Mangweni',
    idNumber: '8907120013081',
    physicalAddress: 'Zwelitsha, King Williams Town',
    borrowerNumber: '0840704310',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 2000,
    interestRate: 60,
    penaltyRate: 5,
    totalRepayment: 3200,
    startDate: '2025-12-01',
    dueDate: '2025-12-23',
    status: RepaymentStatus.OVERDUE,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '40% for Aretha',
    history: [
      { date: '2025-12-01', action: 'Loan Disbursed', amount: 2000 }
    ]
  },
  {
    id: 'T013',
    borrowerName: 'Moyakhe',
    idNumber: '8204200004082',
    physicalAddress: 'Gqeberha, South Africa',
    borrowerNumber: '0815676183',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 1500,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 1950,
    startDate: '2025-12-01',
    dueDate: '2025-12-25',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '20% for Aretha',
    history: [
      { date: '2025-12-01', action: 'Loan Disbursed', amount: 1500 },
      { date: '2025-12-25', action: 'Full Repayment Received', amount: 1950 }
    ]
  },
  {
    id: 'T014',
    borrowerName: 'Nkqwitha',
    idNumber: '9005150015084',
    physicalAddress: 'Qonce, South Africa',
    borrowerNumber: '0789001673',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2025-12-01',
    dueDate: '2025-12-12',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '20% for Aretha',
    history: [
      { date: '2025-12-01', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-12-12', action: 'Full Repayment Received', amount: 520 }
    ]
  },
  {
    id: 'T015',
    borrowerName: 'Tito',
    idNumber: '8511100006085',
    physicalAddress: 'Butterworth, South Africa',
    borrowerNumber: '0605679674',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 5000,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 6500,
    startDate: '2025-12-04',
    dueDate: '2025-12-13',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-04', action: 'Loan Disbursed', amount: 5000 },
      { date: '2025-12-13', action: 'Full Repayment Received', amount: 6500 }
    ]
  },
  {
    id: 'T016',
    borrowerName: 'Ms S Nkila',
    idNumber: '9201010001081',
    physicalAddress: 'East London, South Africa',
    borrowerNumber: '0660710211',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 50,
    penaltyRate: 5,
    totalRepayment: 600,
    startDate: '2025-12-09',
    dueDate: '2025-12-28',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-09', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-12-28', action: 'Full Repayment Received', amount: 600 }
    ]
  },
  {
    id: 'T017',
    borrowerName: 'Agcinile Rigala',
    idNumber: '8802280016083',
    physicalAddress: 'Mthatha, South Africa',
    borrowerNumber: '0718400654',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 5000,
    interestRate: 50,
    penaltyRate: 5,
    totalRepayment: 7500,
    startDate: '2025-12-15',
    dueDate: '2025-12-25',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-15', action: 'Loan Disbursed', amount: 5000 },
      { date: '2025-12-25', action: 'Full Repayment Received', amount: 7500 }
    ]
  },
  {
    id: 'T018',
    borrowerName: 'Aretha',
    idNumber: '9104050012089',
    physicalAddress: 'Beacon Bay, East London',
    borrowerNumber: '0740124606',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 200,
    interestRate: 0,
    penaltyRate: 5,
    totalRepayment: 200,
    startDate: '2025-12-31',
    dueDate: '2026-01-02',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2025-12-31', action: 'Loan Disbursed', amount: 200 },
      { date: '2026-01-02', action: 'Full Repayment Received', amount: 200 }
    ]
  },
  {
    id: 'T019',
    borrowerName: 'Tito',
    idNumber: '8511100006085',
    physicalAddress: 'Butterworth, South Africa',
    borrowerNumber: '0605679674',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 2000,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 2000,
    startDate: '2026-01-10',
    dueDate: '2026-01-12',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2026-01-10', action: 'Loan Disbursed', amount: 2000 },
      { date: '2026-01-12', action: 'Full Repayment Received', amount: 2000 }
    ]
  },
  {
    id: 'T020',
    borrowerName: 'A Mangweni',
    idNumber: '8907120013081',
    physicalAddress: 'Zwelitsha, King Williams Town',
    borrowerNumber: '0840704310',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2026-01-14',
    dueDate: '2026-01-31',
    status: RepaymentStatus.PENDING,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2026-01-14', action: 'Loan Disbursed', amount: 400 }
    ]
  },
  {
    id: 'T021',
    borrowerName: 'Ovayo Sonqishe',
    idNumber: '9801200017085',
    physicalAddress: 'Mthatha, South Africa',
    borrowerNumber: '0673975780',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 300,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 390,
    startDate: '2026-01-14',
    dueDate: '2026-01-31',
    status: RepaymentStatus.PENDING,
    applicationStatus: ApplicationStatus.APPROVED,
    notes: '',
    history: [
      { date: '2026-01-14', action: 'Loan Disbursed', amount: 300 }
    ]
  }
];

export const TRANSLATIONS = {
  [Language.EN]: {
    dashboard: 'Dashboard',
    loans: 'Loans',
    borrowers: 'Borrowers',
    loanCalculator: 'Loan Calculator',
    settings: 'Settings',
    statsDesc: 'Monitor your community lending performance.',
    pending: 'Pending',
    paid: 'Paid',
    overdueStatus: 'Overdue',
    defaulted: 'Defaulted',
    updateSuccess: 'Updated successfully!',
    previous: 'Previous',
    idNumber: 'ID Number',
    fullName: 'Full Name',
    cellNumber: 'Mobile Number',
    quickTemplates: 'Quick Templates',
    amount: 'Principal',
    interest: 'Interest',
    totalDue: 'Total Amount Due',
    amountPaid: 'Amount Paid',
    loanPurpose: 'Purpose of Loan',
    dueDate: 'Due Date',
    payoutMethod: 'Payout Method',
    mobile: 'Mobile',
    bank: 'Bank',
    bankName: 'Bank Name',
    bankAccountNumber: 'Account Number',
    submitApp: 'Submit Application',
    next: 'Next',
    applyNow: 'Apply Now',
    appSuccess: 'Application Submitted!',
    appSuccessDesc: 'Your application has been received and is under review.',
    step: 'Step',
    imaliChat: 'Imali Chat',
    chatIntro: 'Hello! How can I help you today?',
    typeMessage: 'Type a message...',
    totalLoaned: 'Total Loaned',
    repaymentRate: 'Repayment Rate',
    overdue: 'Overdue Loans',
    marketTrends: 'Market Trends',
    fetchMarket: 'Fetch Market Data',
    marketDesc: 'Click to fetch latest SA market trends.',
    riskInsights: 'Risk Insights',
    generateInsights: 'Generate Insights',
    search: 'Search...',
    totalBorrowerLoans: 'Total Loans',
    activeBorrowerLoans: 'Active Loans',
    viewHistory: 'View History',
    calcAmount: 'Loan Amount',
    calcInterest: 'Interest Rate (%)',
    calcDuration: 'Duration (Weeks)',
    calcResult: 'Total to Repay',
    calcPenalty: 'Weekly Penalty',
    borrowerPortfolio: 'Portfolio History',
    txnHistory: 'Transaction History',
    whatsappReminder: 'WhatsApp Reminder',
    principal: 'Principal Amount',
    prefNotifications: 'Notifications',
    prefOverdueAlerts: 'Overdue Alerts',
    prefOverdueDesc: 'Get notified when a loan is overdue.',
    prefSMSAuto: 'WhatsApp Automation',
    prefSMSDesc: 'Send automatic reminders via WhatsApp.',
    prefReports: 'Email Reports',
    prefReportsDesc: 'Weekly summary of your portfolio.',
    prefEmailNewApp: 'Email: New Applications',
    prefEmailNewAppDesc: 'Get an email as soon as a borrower applies.',
    prefEmailOverdue: 'Email: Overdue Payments',
    prefEmailOverdueDesc: 'Get an email alert when a loan misses its due date.',
    intakeTitle: 'New Loan Intake',
    intakeDesc: 'Register a new community borrower.',
    createLoan: 'Create Loan Account',
    editBorrower: 'Edit Borrower Info',
    saveChanges: 'Save Changes',
    confirmReminder: 'Are you sure you want to send a reminder to',
    newCustomer: 'New Customer'
  },
  [Language.XH]: {
    dashboard: 'Ideshibhodi',
    loans: 'Iimali-mboleko',
    borrowers: 'Ababoleki',
    loanCalculator: 'Isibali-mboleko',
    settings: 'Iisetingi',
    statsDesc: 'Jonga indlela iimali zakho ezihamba ngayo.',
    pending: 'Isalindile',
    paid: 'Ihlawulwe',
    overdueStatus: 'Idlulile Ixesha',
    defaulted: 'Ayihlawulwanga',
    updateSuccess: 'Ihlaziywe ngempumelelo!',
    previous: 'Emva',
    idNumber: 'Inombolo ye-ID',
    fullName: 'Igama neFani',
    cellNumber: 'Inombolo yeSelfowuni',
    quickTemplates: 'Iitemplate ezikhawulezayo',
    amount: 'Isiseko (Principal)',
    interest: 'Inzala',
    totalDue: 'Iyonke emayihlawulwe',
    amountPaid: 'Eselihlawulwe',
    loanPurpose: 'Injongo yemali',
    dueDate: 'Umhla wokuhlawula',
    payoutMethod: 'Indlela yokufumana imali',
    mobile: 'Iselula',
    bank: 'Ibhanki',
    bankName: 'Igama leBhanki',
    bankAccountNumber: 'Inombolo yeakhawunti',
    submitApp: 'Thumela isicelo',
    next: 'Phambili',
    applyNow: 'Faka isicelo ngoku',
    appSuccess: 'Isicelo sithunyelwe!',
    appSuccessDesc: 'Isicelo sakho sifunyenwe kwaye sijongiwe.',
    step: 'Inyathelo',
    imaliChat: 'Imali Chat',
    chatIntro: 'Molo! Ndingakunceda ngantoni namhlanje?',
    typeMessage: 'Bhala umyalezo...',
    totalLoaned: 'Iyonke ebolekisiweyo',
    repaymentRate: 'Izinga lokuhlawula',
    overdue: 'Ezidlulileyo ixesha',
    marketTrends: 'Iimeko zemakethi',
    fetchMarket: 'Fumana iinkcukacha',
    marketDesc: 'Cofa apha ukuze ufumane iimeko zamva nje.',
    riskInsights: 'Uhlalutyo lomngcipheko',
    generateInsights: 'Hlaziya uhlalutyo',
    search: 'Khangela...',
    totalBorrowerLoans: 'Iimali zizonke',
    activeBorrowerLoans: 'Ezisebenzayo',
    viewHistory: 'Jonga imbali',
    calcAmount: 'Isixamali semboleko',
    calcInterest: 'Inzala (%)',
    calcDuration: 'Ixesha (Iiveki)',
    calcResult: 'Iyonke ehlawulwayo',
    calcPenalty: 'Isohlwayo ngeveki',
    borrowerPortfolio: 'Imbali yababoleki',
    txnHistory: 'Imbali yeentengiselwano',
    whatsappReminder: 'Isikhumbuzo seWhatsApp',
    principal: 'Isiseko semali',
    prefNotifications: 'Izaziso',
    prefOverdueAlerts: 'Izaziso zezidlulileyo ixesha',
    prefOverdueDesc: 'Fumana isaziso xa imali idlulile ixesha.',
    prefSMSAuto: 'I-WhatsApp Automation',
    prefSMSDesc: 'Thumela izikhumbuzo nge-WhatsApp.',
    prefReports: 'Iingxelo nge-Email',
    prefReportsDesc: 'Isishwankathelo seveki semali yakho.',
    prefEmailNewApp: 'Email: Izicelo Ezintsha',
    prefEmailNewAppDesc: 'Fumana i-email xa umntu efaka isicelo.',
    prefEmailOverdue: 'Email: Ezidlulileyo Ixesha',
    prefEmailOverdueDesc: 'Fumana isaziso se-email xa imali ingahlawulwanga ngexesha.',
    intakeTitle: 'Ukubhalisa umboleki omtsha',
    intakeDesc: 'Bhalisa umboleki omtsha kuluhlu lwasekuhlaleni.',
    createLoan: 'Vula iakhawunti yemali',
    editBorrower: 'Hlela iinkcukacha',
    saveChanges: 'Gcina utshintsho',
    confirmReminder: 'Uqinisekile ukuba ufuna ukuhlawula ku',
    newCustomer: 'Umboleki omtsha'
  }
};
