
import { Loan, RepaymentStatus, PayoutMethod, Language, ApplicationStatus, LoanTemplate } from './types';

export const DEFAULT_INTEREST_RATE = 30;
export const DEFAULT_PENALTY_RATE = 5;

export const LOAN_TEMPLATES: LoanTemplate[] = [
  {
    id: 'startup',
    label: 'Business Stock',
    labelXh: 'Isitokhwe Somsebenzi',
    amount: 5000,
    purpose: 'Buying bulk stock for small business resale.',
    purposeXh: 'Ukuthenga isitokhwe somsebenzi omncinci.'
  },
  {
    id: 'transport',
    label: 'Transport / Taxi',
    labelXh: 'Uthutho / Itekisi',
    amount: 1200,
    purpose: 'Monthly commute and taxi fare for work.',
    purposeXh: 'Imali yothutho yenyanga yomsebenzi.'
  },
  {
    id: 'emergency',
    label: 'Emergency / Household',
    labelXh: 'Ingxakeko / Ikhaya',
    amount: 800,
    purpose: 'Urgent household repairs or grocery shortfall.',
    purposeXh: 'Iinkcitho zangaphakathi ezingalindelekanga.'
  },
  {
    id: 'education',
    label: 'School Fees / Stationery',
    labelXh: 'Imfundo / Iincwadi',
    amount: 2500,
    purpose: 'School uniforms, books, or registration fees.',
    purposeXh: 'Iyunifomu yesikolo, iincwadi okanye umrhumo.'
  }
];

export const SA_BANKS = [
  'Standard Bank', 'First National Bank (FNB)', 'Absa', 'Nedbank', 'Capitec Bank',
  'TymeBank', 'Discovery Bank', 'Bank Zero', 'African Bank', 'Investec',
  'Bidvest Bank', 'Sasfin Bank', 'Grindrod Bank', 'Postbank', 'Old Mutual Bank',
  'Mercantile Bank', 'Al Baraka Bank', 'HBZ Bank', 'Access Bank South Africa'
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'T001',
    borrowerName: 'Ms S Nkila',
    idNumber: '9201010001081',
    physicalAddress: 'East London, South Africa',
    borrowerNumber: '0660710211',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 400,
    interestRate: 30,
    penaltyRate: 5,
    totalRepayment: 520,
    startDate: '2025-11-15',
    dueDate: '2025-12-01',
    status: RepaymentStatus.PAID,
    applicationStatus: ApplicationStatus.APPROVED,
    history: [
      { date: '2025-11-15', action: 'Loan Disbursed', amount: 400 },
      { date: '2025-12-01', action: 'Full Repayment Received', amount: 520 }
    ]
  },
  {
    id: 'T011',
    borrowerName: 'U Zokhela',
    idNumber: '9611200014087',
    physicalAddress: 'Mdantsane, South Africa',
    borrowerNumber: '0730713439',
    payoutMethod: PayoutMethod.MOBILE,
    amountLoaned: 3000,
    interestRate: 60,
    penaltyRate: 5,
    totalRepayment: 4800,
    startDate: '2025-12-01',
    dueDate: '2025-12-20',
    status: RepaymentStatus.OVERDUE,
    applicationStatus: ApplicationStatus.APPROVED,
    history: [
      { date: '2025-12-01', action: 'Loan Disbursed', amount: 3000 }
    ]
  }
];

export const TRANSLATIONS = {
  [Language.EN]: {
    dashboard: 'Dashboard',
    loans: 'Loans',
    borrowers: 'Borrowers',
    loanCalculator: 'Loan Calculator',
    settings: 'Settings',
    statsDesc: 'Monitor your community lending performance.',
    pending: 'Pending',
    paid: 'Paid',
    overdueStatus: 'Overdue',
    defaulted: 'Defaulted',
    updateSuccess: 'Updated successfully!',
    previous: 'Previous',
    idNumber: 'ID Number',
    fullName: 'Full Name',
    cellNumber: 'Mobile Number',
    quickTemplates: 'Quick Templates',
    amount: 'Principal',
    interest: 'Interest',
    totalDue: 'Total Amount Due',
    amountPaid: 'Amount Paid',
    loanPurpose: 'Purpose of Loan',
    dueDate: 'Due Date',
    payoutMethod: 'Payout Method',
    mobile: 'Mobile',
    bank: 'Bank',
    bankName: 'Bank Name',
    bankAccountNumber: 'Account Number',
    submitApp: 'Submit Application',
    next: 'Next',
    applyNow: 'Apply Now',
    appSuccess: 'Application Submitted!',
    appSuccessDesc: 'Your application has been received and is under review.',
    step: 'Step',
    imaliChat: 'Imali Chat',
    chatIntro: 'Hello! How can I help you today?',
    typeMessage: 'Type a message...',
    totalLoaned: 'Total Loaned',
    repaymentRate: 'Repayment Rate',
    overdue: 'Overdue Loans',
    marketTrends: 'Market Trends',
    fetchMarket: 'Fetch Market Data',
    marketDesc: 'Click to fetch latest SA market trends.',
    riskInsights: 'Risk Insights',
    generateInsights: 'Generate Insights',
    search: 'Search...',
    totalBorrowerLoans: 'Total Loans',
    activeBorrowerLoans: 'Active Loans',
    viewHistory: 'View History',
    calcAmount: 'Loan Amount',
    calcInterest: 'Interest Rate (%)',
    calcDuration: 'Duration (Weeks)',
    calcResult: 'Total to Repay',
    calcPenalty: 'Weekly Penalty',
    borrowerPortfolio: 'Portfolio History',
    txnHistory: 'Transaction History',
    whatsappReminder: 'WhatsApp Reminder',
    principal: 'Principal Amount',
    prefNotifications: 'Notifications',
    prefOverdueAlerts: 'Overdue Alerts',
    prefOverdueDesc: 'Get notified when a loan is overdue.',
    prefSMSAuto: 'WhatsApp Automation',
    prefSMSDesc: 'Send automatic reminders via WhatsApp.',
    prefSMSUpdates: 'SMS Status Updates',
    prefSMSUpdatesDesc: 'Send automated SMS when loan status changes.',
    prefEmailUpdates: 'Email Status Updates',
    prefEmailUpdatesDesc: 'Send automated emails when loan status changes.',
    prefReports: 'Email Reports',
    prefReportsDesc: 'Weekly summary of your portfolio sent to montiovayo@gmail.com.',
    prefEmailNewApp: 'Email: New Applications',
    prefEmailNewAppDesc: 'Get an email as soon as a borrower applies.',
    prefEmailOverdue: 'Email: Overdue Payments',
    prefEmailOverdueDesc: 'Get an email alert when a loan misses its due date.',
    intakeTitle: 'New Loan Intake',
    intakeDesc: 'Register a new community borrower.',
    createLoan: 'Create Loan Account',
    editBorrower: 'Edit Borrower Info',
    saveChanges: 'Save Changes',
    confirmReminder: 'Are you sure you want to send a reminder to',
    newCustomer: 'New Customer',
    sendNotifications: 'Send Notifications',
    notifSent: 'Notifications sent successfully!',
    sendingNotifs: 'Sending community alerts...'
  },
  [Language.XH]: {
    dashboard: 'Ideshibhodi',
    loans: 'Iimali-mboleko',
    borrowers: 'Ababoleki',
    loanCalculator: 'Isibali-mboleko',
    settings: 'Iisetingi',
    statsDesc: 'Jonga indlela iimali zakho ezihamba ngayo.',
    pending: 'Isalindile',
    paid: 'Ihlawulwe',
    overdueStatus: 'Idlulile Ixesha',
    defaulted: 'Ayihlawulwanga',
    updateSuccess: 'Ihlaziywe ngempumelelo!',
    previous: 'Emva',
    idNumber: 'Inombolo ye-ID',
    fullName: 'Igama neFani',
    cellNumber: 'Inombolo yeSelfowuni',
    quickTemplates: 'Iitemplate ezikhawulezayo',
    amount: 'Isiseko (Principal)',
    interest: 'Inzala',
    totalDue: 'Iyonke emayihlawulwe',
    amountPaid: 'Eselihlawulwe',
    loanPurpose: 'Injongo yemali',
    dueDate: 'Umhla wokuhlawula',
    payoutMethod: 'Indlela yokufumana imali',
    mobile: 'Iselula',
    bank: 'Ibhanki',
    bankName: 'Igama leBhanki',
    bankAccountNumber: 'Inombolo yeakhawunti',
    submitApp: 'Thumela isicelo',
    next: 'Phambili',
    applyNow: 'Faka isicelo ngoku',
    appSuccess: 'Isicelo sithunyelwe!',
    appSuccessDesc: 'Isicelo sakho sifunyenwe kwaye sijongiwe.',
    step: 'Inyathelo',
    imaliChat: 'Imali Chat',
    chatIntro: 'Molo! Ndingakunceda ngantoni namhlanje?',
    typeMessage: 'Bhala umyalezo...',
    totalLoaned: 'Iyonke ebolekisiweyo',
    repaymentRate: 'Izinga lokuhlawula',
    overdue: 'Ezidlulileyo ixesha',
    marketTrends: 'Iimeko zemakethi',
    fetchMarket: 'Fumana iinkcukacha',
    marketDesc: 'Cofa apha ukuze ufumane iimeko zamva nje.',
    riskInsights: 'Uhlalutyo lomngcipheko',
    generateInsights: 'Hlaziya uhlalutyo',
    search: 'Khangela...',
    totalBorrowerLoans: 'Iimali zizonke',
    activeBorrowerLoans: 'Ezisebenzayo',
    viewHistory: 'Jonga imbali',
    calcAmount: 'Isixamali semboleko',
    calcInterest: 'Inzala (%)',
    calcDuration: 'Ixesha (Iiveki)',
    calcResult: 'Iyonke ehlawulwayo',
    calcPenalty: 'Isohlwayo ngeveki',
    borrowerPortfolio: 'Imbali yababoleki',
    txnHistory: 'Imbali yeentengiselwano',
    whatsappReminder: 'Isikhumbuzo seWhatsApp',
    principal: 'Isiseko semali',
    prefNotifications: 'Izaziso',
    prefOverdueAlerts: 'Izaziso zezidlulileyo ixesha',
    prefOverdueDesc: 'Fumana isaziso xa imali idlulile ixesha.',
    prefSMSAuto: 'I-WhatsApp Automation',
    prefSMSDesc: 'Thumela izikhumbuzo nge-WhatsApp.',
    prefSMSUpdates: 'Izaziso ze-SMS',
    prefSMSUpdatesDesc: 'Thumela i-SMS xa imeko yemali itshintsha.',
    prefEmailUpdates: 'Izaziso ze-Email',
    prefEmailUpdatesDesc: 'Thumela i-email xa imeko yemali itshintsha.',
    prefReports: 'Iingxelo nge-Email',
    prefReportsDesc: 'Isishwankathelo seveki semali zakho sithunyelwa ku-montiovayo@gmail.com.',
    prefEmailNewApp: 'Email: Izicelo Ezintsha',
    prefEmailNewAppDesc: 'Fumana i-email xa umntu efaka isicelo.',
    prefEmailOverdue: 'Email: Ezidlulileyo Ixesha',
    prefEmailOverdueDesc: 'Fumana isaziso se-email xa imali ingahlawulwanga ngexesha.',
    intakeTitle: 'Ukubhalisa umboleki omtsha',
    intakeDesc: 'Bhalisa umboleki omtsha kuluhlu lwasekuhlaleni.',
    createLoan: 'Vula iakhawunti yemali',
    editBorrower: 'Hlela iinkcukacha',
    saveChanges: 'Gcina utshintsho',
    confirmReminder: 'Uqinisekile ukuba ufuna ukuhlawula ku',
    newCustomer: 'Umboleki omtsha',
    sendNotifications: 'Thumela Izaziso',
    notifSent: 'Izaziso zithunyelwe ngempumelelo!',
    sendingNotifs: 'Kuthunyelwa izaziso...'
  }
};
